In [1]:
from datetime import datetime
import pandas

/home/gram/.local/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
df = pandas.read_json('./pythonetc.ndjson', lines=True)
df.head()

,id,date,text,views,forwards,buttons
0,684,2021-12-13 19:24:09+00:00,,3278,10,{'Donate': 0}
1,682,2021-12-13 19:24:05+00:00,"Finally, you can express your gratitude toward...",3288,2,{}
2,681,2021-12-13 19:23:59+00:00,,3303,3,{}
3,680,2021-12-13 19:23:54+00:00,You are also welcome to consider joining my te...,3278,2,{}
4,679,2021-12-13 19:23:49+00:00,Hi there! As you‚Äôve probably already noticed t...,3235,3,{}

In [3]:
df['likes'] = df.buttons.apply(lambda x: x.get('üëç', 0))
df['dislikes'] = df.buttons.apply(lambda x: x.get('üëé', 0))

In [4]:
YEAR = datetime.now().year

Filter posts published in this year, filter out posts without text, and sort the result by forwards count.

In [5]:
df[(df.date.dt.year == YEAR) & (df.text != "")].sort_values(by='forwards', ascending=False)[:10]

,id,date,text,views,forwards,buttons,likes,dislikes
35,646,2021-01-27 16:01:01+00:00,Today Guido van Rossum posted a Python riddle:...,6740,111,"{'üëç': 149, 'üëé': 11}",149,11
7,676,2021-08-26 15:00:16+00:00,Python 3.7 introduced Development Mode. The mo...,7119,53,"{'üëç': 181, 'üëé': 0}",181,0
29,652,2021-03-11 15:00:10+00:00,"Suppose, you have 10 lists:\n\nlists = [list(r...",5530,50,"{'üëç': 236, 'üëé': 3}",236,3
31,650,2021-03-04 15:00:15+00:00,Let's learn a bit more about strings performan...,5205,44,"{'üëç': 166, 'üëé': 2}",166,2
23,658,2021-04-01 15:00:08+00:00,"In most of the programming languages (like C, ...",4938,36,"{'üëç': 136, 'üëé': 7}",136,7
25,656,2021-03-25 15:00:07+00:00,PEP-589 (landed in Python 3.8) introduced typi...,5063,34,"{'üëç': 146, 'üëé': 4}",146,4
28,653,2021-03-16 15:01:07+00:00,"Starting Python 3.8, the interpreter warns abo...",4503,33,"{'üëç': 170, 'üëé': 1}",170,1
19,662,2021-04-20 15:01:07+00:00,"When something fails, usually you want to log ...",4271,26,"{'üëç': 126, 'üëé': 3}",126,3
16,666,2021-04-29 15:00:06+00:00,If any function can modify any passed argument...,6759,22,"{'üëç': 129, 'üëé': 1}",129,1
17,665,2021-04-27 15:00:41+00:00,Multiline string literal preserves every symbo...,4747,22,"{'üëç': 136, 'üëé': 7}",136,7